# Rename this file to languages.toml to enable multilingual support
# Original file name: _languages.toml
[en]
languageName = "English"
languagedirection = "ltr"
title = "LiAuTraver's Corner"
weight = 1

[zh]
languageName = "Chinese"
languagedirection = "ltr"
title = "LiAuTraver's Corner"
weight = 2

[de]
languageName = "Deitsch"
languagedirection = "ltr"
title = "LiAuTraver's Corner"
weight = 3
