# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

#disable social menu
#[[social]]
#identifier = "github"
#name = "GitHub"
#url = "https://github.com/LiAuTraver"
#
#[social.params]
#icon = "brand-github"
#
#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com/0xLiAuTraver"
#
#[social.params]
#icon = "brand-twitter"
